# -*- coding: utf-8 -*-
"""
/***************************************************************************
 multiplicate_layer_by_attribute
                                 A QGIS plugin
 Manage Parcs i Jardins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-18
        copyright            : (C) 2026 by PSIG
        email                : geraldo@servus.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load multiplicate_layer_by_attribute class from file multiplicate_layer_by_attribute.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .multiplicate_layer_by_attribute import multiplicate_layer_by_attribute
    return multiplicate_layer_by_attribute(iface)
